### ISSUE TITLE
Can't change resolution

### ISSUE THREAD

**Issue by Ecthelion75** [sunenielsen/tribaltrouble#31]
![image_2024-12-13_153612639](https://github.com/user-attachments/assets/c729d7f5-2ef3-4205-af4a-1339490e62f4)

I can't change resolution, is there a settings file available? I am using Windows 11.

**Comment by veslav3** [comment]
@Ecthelion75 have you found the solution and if so, can you share it for someone else to find the answer?

**Comment by Ecthelion75** [comment]
Go to C:\Users\Username\OneDrive\TribalTrouble and delete settings file for Windows.
