### ISSUE TITLE
How do I contribute the work that I've done...

### ISSUE THREAD

**Issue by team-penguin** [sunenielsen/tribaltrouble#8]
I have figured out how to run the matchmaker, router and registration services. I have added (1) line of code to expose the password hash when the game is registered. I needed to do this because the registration hangs and doesn't insert values into the database, but does progress far enough to grab the password hash.  I can then manually insert users and complete the registratoin. Multiplayer works without any issues and the Single Player game works with the caveat that I have to run the client from the source directory. The game binaries seem to be built with a different password or other mechanism that prevents them from being recognized as the current version.

That is what I have, what would people like to see?

**Comment by cryptid11** [comment]
I try to follow the instructions, here the log:

(Is anybody able to post further instruction for noobs?)

trying to create database I get:

MariaDB [oddlabs]> CREATE TABLE match_user (
    -> username varchar(20) NOT NULL,
    -> id int(11) NOT NULL,
    -> reg_key varchar(20) NOT NULL,
    -> password varchar(40) NOT NULL,
    -> email varchar(60) NOT NULL,
    -> last_used_profile int(10) default NULL,
    -> banned_until datetime NOT NULL default '0000-00-00 00:00:00',
    -> PRIMARY KEY (username),
    -> UNIQUE KEY (reg_key),
    -> INDEX (banned_until),
    -> FOREIGN KEY (id,reg_key) REFERENCES registrations (id,reg_key)
    -> ) ENGINE=InnoDB;
ERROR 1005 (HY000): Can't create table `oddlabs`.`match_user` (errno: 150 "Foreign key constraint is incorrectly formed")

And adding:

```
if (!login.isValid())
    gui_root.addModalForm(new MessageForm(Utils.getBundleString(bundle, "invalid_login")));
else
    System.out.println("team-penguin: username = " + username + ", password = " + CryptUtils.digest(login.getPasswordDigest()) + ", " + login_details.getEmail() + ", pw_digest = " + password + ", " + login.getUsername()); doCreateUser(username, login_details, password, login); } }
```

to tribaltrouble/tt/classes/com/oddlabs/tt/form/NewUserForm.java I got:

/tribaltrouble/common/common.xml:37: Compile failed; see the compiler error output for details.

**Comment by team-penguin** [comment]
Regarding: ERROR 1005 (HY000): Can't create table oddlabs.match_user (errno: 150 "Foreign key constraint is incorrectly formed")

The registrations table needs to be populated with a valid id and reg_key.
The 3rd post above yours has sample SQL for inserting user data into the registrations table.

The compile error is environmental, maybe you don't have javac in your path.
Also, ensure that you include

import com.oddlabs.util.CryptUtils;

in the file: ./tt/classes/com/oddlabs/tt/form/NewUserForm.java
